version: '3.8'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MARIADB_USER=root
      - MARIADB_PASSWORD=Flask
      - MARIADB_SERVER=mariadb
      - MARIADB_DB=coma
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Flask
      MYSQL_DATABASE: coma
      MYSQL_USER: root
      MYSQL_PASSWORD: Flask
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
