version: '3'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MARIADB_USER=sa-coma
      - MARIADB_PASSWORD=Flask
      - MARIADB_SERVER=mariadb
      - MARIADB_DB=coma

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Flask
      MYSQL_DATABASE: coma
      MYSQL_USER: cs-coma
      MYSQL_PASSWORD: Flask
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
